#!/usr/bin/env bash

# create virtualenvs from scratch with a compiled python

# to make sure all the 'necessary bits' of python get compiled,
# on debianlike distros (tested ubuntu 13.04), you should probably:
#     * make sure deb-src repos are enabled
#     * aptitude build-dep [2.7/3.3]
# for some reason, it doesn't seem to pull in curses:
#     * aptitude install libncurses-dev

BASE="$HOME/.python"
# pythons go here
PY_PREFIX="$BASE/pythons"
# virtualenvs go here
VENV_PREFIX="$BASE/venvs"

usage() {
cat <<EOF
usage: $(basename $0) [-3] [virtualenv_name]
        pythons: $PY_PREFIX
    virtualenvs: $VENV_PREFIX
EOF
}

case $1 in
    -h|--help) usage; exit;;
    -3.3.2)
        shift
        PY_VERSION=3.3.2
        PY_URL=http://www.python.org/ftp/python/3.3.2
        PY_TGZ=Python-3.3.2.tgz
        PY_TGZ_MD5=0a2ea57f6184baf45b150aee53c0c8da
        PY_SRC=Python-3.3.2
        PY_EXE=python3.3
        ;;
    -3.4.1) # latest
        shift
        PY_VERSION=3.4.1
        PY_URL=https://www.python.org/ftp/python/3.4.1
        PY_TGZ=Python-3.4.1.tgz
        PY_TGZ_MD5=26695450087f8587b26d0b6a63844af5
        PY_SRC=Python-3.4.1
        PY_EXE=python3.4
        ;;
    -2.7.5)
        shift
        PY_VERSION=2.7.5
        PY_URL=http://www.python.org/ftp/python/2.7.5
        PY_TGZ=Python-2.7.5.tgz
        PY_TGZ_MD5=b4f01a1d0ba0b46b05c73b2ac909b1df
        PY_SRC=Python-2.7.5
        PY_EXE=python2.7
        ;;
     -2.7.8)
        shift
        PY_VERSION=2.7.8
        PY_URL=https://www.python.org/ftp/python/2.7.8
        PY_TGZ_MD5=d4bca0159acb0b44a781292b5231936f
        PY_TGZ=Python-2.7.8.tgz
        PY_SRC=Python-2.7.8
        PY_EXE=python2.7
        ;;
     -2.7.9)
        shift
        PY_VERSION=2.7.9
        PY_URL=https://www.python.org/ftp/python/2.7.9
        PY_TGZ_MD5=5eebcaa0030dc4061156d3429657fb83
        PY_TGZ=Python-2.7.9.tgz
        PY_SRC=Python-2.7.9
        PY_EXE=python2.7
        ;;
     *) # latest
        shift
        PY_VERSION=2.7.11
        PY_URL=https://www.python.org/ftp/python/2.7.11
        PY_TGZ_MD5=6b6076ec9e93f05dd63e47eb9c15728b
        PY_TGZ=Python-2.7.11.tgz
        PY_SRC=Python-2.7.11
        PY_EXE=python2.7
        ;;
esac

# virtualenv
VENV_URL=https://pypi.python.org/packages/source/v/virtualenv
VENV_EXE=virtualenv.py

#VENV_FILE=virtualenv-1.10.tar.gz
#VENV_TGZ_MD5=9745c28256c70c76d36adb3767a00212
#VENV_SRC=virtualenv-1.10

#VENV_TGZ=virtualenv-12.0.4.tar.gz
#VENV_TGZ_MD5=ce7c4025516806b791bbd5b4ff6c4b84
#VENV_SRC=virtualenv-12.0.4

#VENV_TGZ=virtualenv-12.1.1.tar.gz
#VENV_TGZ_MD5=901ecbf302f5de9fdb31d843290b7217
#VENV_SRC=virtualenv-12.1.1

VENV_TGZ=virtualenv-15.0.1.tar.gz
VENV_TGZ_MD5=28d76a0d9cbd5dc42046dd14e76a6ecc
VENV_SRC=virtualenv-15.0.1

check_md5() {
    case $(uname) in
        Darwin) md5=$(md5 -q "$1");;
        Linux) md5=$(md5sum "$1");;
    esac
    [ "${md5%% *}" = "$2" ] && return
    echo "$1 md5 doesn't match"
    return 1
}

ensure_python() {
    mkdir -p "$PY_PREFIX"
    cd "$BASE"
    [ "$PWD" = "$BASE" ] || {
        echo "Can't find $BASE"
        return 1
    }

    [ -f "$PY_TGZ" ] || wget "$PY_URL/$PY_TGZ"
    [ -d "$PY_SRC" ] || tar xvf "$PY_TGZ"

    check_md5 "$PY_TGZ" "$PY_TGZ_MD5" || return 1

    [ -f "$PY_PREFIX/$PY_VERSION/bin/$PY_EXE" ] || {
        cd "$PY_SRC"
        [ "$PWD" = "$BASE/$PY_SRC" ] || {
            echo "Can't find $BASE/$PY_SRC"
            return 1
        }

        # take a wide stance
        FLAGS='--enable-unicode=ucs4'

        case $(uname) in
            Darwin)
                # without this >=10.6 it won't try to build readline module
                FLAGS="$FLAGS MACOSX_DEPLOYMENT_TARGET=10.8"
            ;;
        esac

        ./configure $FLAGS --prefix="$PY_PREFIX/$PY_VERSION"
        make

        # So you can review if all the 'necessary bits' are compiled
        read -p "Continue with install? [y/N] " REPLY
        [ "$REPLY" = "y" -o "$REPLY" = "Y" ] || return 1

        make altinstall
    }
}

ensure_virtualenv() {
    [ -f "$PY_PREFIX/$PY_VERSION/bin/$PY_EXE" ] || {
        echo "Cant' find $PY_PREFIX/$PY_VERSION/bin/$PY_EXE"
        return 1
    }

    cd "$BASE"
    [ "$PWD" = "$BASE" ] || {
        echo "Can't find $BASE"
        return 1
    }

    [ -f "$VENV_TGZ" ] || curl -O "$VENV_URL/$VENV_TGZ"
    check_md5 "$VENV_TGZ" "$VENV_TGZ_MD5" || return 1
    [ -d "$VENV_SRC" ] || tar xvfz "$VENV_TGZ"

    [ "$1" ] || return

    [ -d "$VENV_PREFIX" ] || mkdir -p "$VENV_PREFIX"

    [ -d "$VENV_PREFIX/$1" ] && return

    "$PY_PREFIX/$PY_VERSION/bin/$PY_EXE" "$VENV_SRC/$VENV_EXE" "$VENV_PREFIX/$1"
}

[ "$VIRTUAL_ENV" ] && {
    echo "probably not a good idea to run this in a virtualenv"
    exit
}

ensure_python || exit
ensure_virtualenv "$1"
